
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svqjeqngyindshuxjurp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cWplcW5neWluZHNodXhqdXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTcwMjgsImV4cCI6MjA1OTkzMzAyOH0.IAjaLkfO-wzYh9LzfF6tkYS2VPLHVkbewut2pu0Y67E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
    detectSessionInUrl: true,
    flowType: 'implicit',
    debug: true // Enable debug mode to log authentication issues
  }
});

// Add a helper function to verify admin status
export const isUserAdmin = async (): Promise<boolean> => {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return false;
    
    // First check user metadata
    const userRole = session.user.user_metadata?.role;
    if (userRole === 'admin') return true;
    
    // If not in metadata, try to get from profiles table
    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', session.user.id)
      .single();
      
    return profile?.role === 'admin';
  } catch (error) {
    console.error('Error checking admin status:', error);
    return false;
  }
};
