
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svqjeqngyindshuxjurp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cWplcW5neWluZHNodXhqdXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTcwMjgsImV4cCI6MjA1OTkzMzAyOH0.IAjaLkfO-wzYh9LzfF6tkYS2VPLHVkbewut2pu0Y67E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Add debug helper that logs all auth state changes with more detailed information
supabase.auth.onAuthStateChange((event, session) => {
  console.log("[Supabase Debug] Auth state changed:", event);
  if (session?.user) {
    console.log("[Supabase Debug] User ID:", session.user.id);
    console.log("[Supabase Debug] User email:", session.user.email);
    console.log("[Supabase Debug] User metadata:", session.user.user_metadata);
  } else {
    console.log("[Supabase Debug] No active session");
  }
});

// Additional debug function to check profile data
export const checkProfileData = async (userId: string) => {
  const { data, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', userId)
    .single();
    
  if (error) {
    console.error("[Profile Debug] Error fetching profile:", error);
    return null;
  }
  
  console.log("[Profile Debug] Profile data:", data);
  return data;
};

// Helper function to get a public URL for a file in storage
export const getPublicUrl = (bucket: string, path: string): string => {
  const { data } = supabase.storage.from(bucket).getPublicUrl(path);
  return data.publicUrl;
};

// Helper function to upload a file to storage
export const uploadFile = async (
  bucket: string, 
  path: string, 
  file: File,
  onProgress?: (progress: number) => void
): Promise<{ url: string; path: string } | null> => {
  try {
    // Check if the user is authenticated
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      console.error('[Storage Debug] User is not authenticated');
      throw new Error('User is not authenticated');
    }

    console.log('[Storage Debug] Starting upload to bucket:', bucket, 'path:', path);
    
    // Simple progress tracking - we'll use a manual approach since onUploadProgress is not available
    if (onProgress) {
      // Start progress indicator
      onProgress(10);
    }
    
    // Upload file with cacheControl and upsert options
    const { data, error } = await supabase.storage
      .from(bucket)
      .upload(path, file, {
        cacheControl: '3600',
        upsert: true
      });

    // Update progress to simulate completion
    if (onProgress) {
      onProgress(100);
    }

    if (error) {
      console.error('[Storage Debug] Upload error:', error);
      throw error;
    }

    if (!data) {
      throw new Error('Upload returned no data');
    }

    const url = getPublicUrl(bucket, data.path);
    console.log('[Storage Debug] File uploaded successfully:', { path: data.path, url });
    
    return { url, path: data.path };
  } catch (error) {
    console.error('[Storage Debug] Error in uploadFile:', error);
    return null;
  }
};

// Helper function to delete a file from storage
export const deleteFile = async (bucket: string, path: string): Promise<boolean> => {
  try {
    // Check if the user is authenticated
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      console.error('[Storage Debug] User is not authenticated for deletion');
      throw new Error('User is not authenticated');
    }

    console.log('[Storage Debug] Attempting to delete file from bucket:', bucket, 'path:', path);
    
    const { error } = await supabase.storage
      .from(bucket)
      .remove([path]);

    if (error) {
      console.error('[Storage Debug] Delete error:', error);
      throw error;
    }

    console.log('[Storage Debug] File deleted successfully:', path);
    return true;
  } catch (error) {
    console.error('[Storage Debug] Error in deleteFile:', error);
    return false;
  }
};

// Project-specific database operations
export const projectOperations = {
  // Fetch all projects
  fetchProjects: async () => {
    const { data, error } = await supabase
      .from('projects')
      .select('*')
      .order('created_at', { ascending: false });
    
    if (error) {
      console.error('[Project Debug] Error fetching projects:', error);
      throw error;
    }
    
    return data;
  },
  
  // Add a new project
  addProject: async (projectData: any, userId: string) => {
    try {
      console.log('[Project Debug] Adding project with user ID:', userId);
      
      const { data, error } = await supabase
        .from('projects')
        .insert({
          ...projectData,
          user_id: userId
        })
        .select()
        .single();
        
      if (error) {
        console.error('[Project Debug] Error adding project:', error);
        throw error;
      }
      
      return data;
    } catch (error) {
      console.error('[Project Debug] Exception in addProject:', error);
      throw error;
    }
  },
  
  // Update an existing project
  updateProject: async (projectId: string, projectData: any, userId: string) => {
    try {
      console.log('[Project Debug] Updating project with ID:', projectId, 'User ID:', userId);
      
      const { data, error } = await supabase
        .from('projects')
        .update({
          ...projectData,
          updated_at: new Date().toISOString()
        })
        .eq('id', projectId)
        .select()
        .single();
        
      if (error) {
        console.error('[Project Debug] Error updating project:', error);
        throw error;
      }
      
      return data;
    } catch (error) {
      console.error('[Project Debug] Exception in updateProject:', error);
      throw error;
    }
  },
  
  // Delete a project
  deleteProject: async (projectId: string, userId: string) => {
    try {
      console.log('[Project Debug] Deleting project with ID:', projectId, 'User ID:', userId);
      
      // First, get the project to access its images
      const { data: project, error: fetchError } = await supabase
        .from('projects')
        .select('cover_image, screenshots')
        .eq('id', projectId)
        .single();
      
      if (fetchError) {
        console.error('[Project Debug] Error fetching project for deletion:', fetchError);
      } else if (project) {
        // Delete cover image if it exists and is from Supabase
        if (project.cover_image && project.cover_image.includes('project-images')) {
          const coverPath = project.cover_image.split('/project-images/')[1];
          if (coverPath) {
            await deleteFile('project-images', coverPath).catch(err => 
              console.error('[Project Debug] Error deleting cover image:', err)
            );
          }
        }
        
        // Delete all screenshots if they exist and are from Supabase
        if (project.screenshots && project.screenshots.length > 0) {
          for (const screenshot of project.screenshots) {
            if (screenshot && screenshot.includes('project-images')) {
              const screenshotPath = screenshot.split('/project-images/')[1];
              if (screenshotPath) {
                await deleteFile('project-images', screenshotPath).catch(err => 
                  console.error('[Project Debug] Error deleting screenshot:', err)
                );
              }
            }
          }
        }
      }
      
      // Now delete the project
      const { error } = await supabase
        .from('projects')
        .delete()
        .eq('id', projectId);
        
      if (error) {
        console.error('[Project Debug] Error deleting project from database:', error);
        throw error;
      }
      
      console.log('[Project Debug] Project deleted successfully:', projectId);
      return true;
    } catch (error) {
      console.error('[Project Debug] Exception in deleteProject:', error);
      throw error;
    }
  }
};

// Check if the storage buckets exist, create them if they don't
export const ensureStorageBuckets = async () => {
  try {
    console.log('[Storage Debug] Checking for required storage buckets');
    
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    if (error) {
      console.error('[Storage Debug] Error listing buckets:', error);
      return;
    }
    
    const requiredBuckets = ['project-images'];
    const existingBuckets = buckets.map(b => b.name);
    
    for (const bucket of requiredBuckets) {
      if (!existingBuckets.includes(bucket)) {
        console.log(`[Storage Debug] Creating bucket: ${bucket}`);
        const { error: createError } = await supabase.storage.createBucket(bucket, {
          public: true
        });
        
        if (createError) {
          console.error(`[Storage Debug] Error creating bucket ${bucket}:`, createError);
        } else {
          console.log(`[Storage Debug] Bucket ${bucket} created successfully`);
        }
      } else {
        console.log(`[Storage Debug] Bucket ${bucket} already exists`);
      }
    }
  } catch (error) {
    console.error('[Storage Debug] Exception in ensureStorageBuckets:', error);
  }
};

// Initialize storage buckets when the client is imported
ensureStorageBuckets();
